# Generated by Django 3.0 on 2022-03-15 00:31

import app_productos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=4)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to=app_productos.models.url_producto)),
                ('fk_categoria', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_productos.Categoria')),
            ],
        ),
    ]
